name: "Run"
on: [pull_request, push]

jobs:
  defaults:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: mymindstorm/setup-emsdk@master

    - name: Verify
      run: emcc -v
  actions-use-cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache emsdk
        uses: actions/cache@v1
        id: cache
        with:
          path: emsdk-cache
          key: ${{ runner.os }}-emsdk-1.38.48
      - name: Setup emsdk (use cache if found, create otherwise)  
        uses: mymindstorm/setup-emsdk@master
        with:
          version: 1.38.48
          actions-cache-folder: 'emsdk-cache'
          cache-hit: ${{steps.cache.outputs.cache-hit}}
          no-cache: true
          
      - name: Verify
        run: emcc -v
  no-install:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@master
        with:
          no-install: true

      - name: Verify
        run: emsdk list
